---
title: "Income disparity, ranking and number of tax filers across the TN counties from 2011-2015. "
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library("MASS")
library("dplyr")
library("ggplot2")
library("grid")
library("stringr")
library("reshape2")


```

Column {data-width=650}
-----------------------------------------------------------------------

### Income disparity among TN counties

```{r echo=FALSE}
irs_2011_2015 <- readRDS('./r-objects/irs_2011_2015.rds')
df_sort <- irs_2011_2015 %>% 
  filter(income_per_tax_return >= 8) %>% 
  select(county, year, income_per_tax_return)
h <- hist(df_sort$income_per_tax_return, breaks=10, plot=FALSE)
cuts <- cut(h$breaks, c(-Inf, 9, 19, 23, 25, Inf))
plot(
  h, 
  col=c('#062F4F', '#6D7993', '#B82601', '#6D7993', '#B82601')[cuts],
  main = '',
  xlab = 'Household Income Range * 1000',
  ylab = 'County Frequency'
)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Is there any change in income over the years?

```{r irs_2011_2015, echo = FALSE}
df_sort <- irs_2011_2015 %>% 
  filter(income_per_tax_return >= 8) %>% 
  select(
    county, year, income_per_tax_return
  )
df_sort %>% 
  ggplot(
    aes(
      x = year,
      y = income_per_tax_return, 
      group = county, 
      color = county
    )
  ) + geom_line(size = 1.5) + 
  labs(y = "Income Per Tax Return * 1000", x = "Years")
```

### Is there any change in number of tax fiilers across the years?

```{r}
ggplot_num_returns <- function(df, range, y.label="") {
  df_sort_1 <- irs_2011_2015 %>% 
    dplyr::filter(sum_total_income_returns >= range) %>% 
    dplyr::select(
      county, year, sum_total_income_returns
    )
  
  df_sort_1 %>% 
    ggplot(
      aes(
        x = year,
        y = sum_total_income_returns, 
        group = county,
        color = county
      )
    ) + 
    geom_line(size = 1.5) + 
    labs(y = y.label, x = "") +
    theme(axis.text.x = element_text(
        face = 'bold', 
        size = 14
      )
    ) +
    theme(axis.text.y = element_text(
        face = 'bold', 
        size = 14
      )
    ) +
    theme(axis.title.y = element_text(
        size = 20
      )
    ) +
    scale_y_continuous(labels = scales::comma) +
    scale_color_hue(l = 60, c = 50)
}
ggplot_num_returns(irs_2011_2015, 20000, y.label = "Num of Tax Payers Per Year")
```

